
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine

  web:
    build: .
    depends_on:
      - db
      - redis
    ports:
      - "5000:5000"